version: '3.9'

services:
  ai-structurizer:
    build:
      context: .
      dockerfile: Dockerfile
    image: ai-structurizer:latest
    container_name: ai-structurizer
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - OPENAI_API_KEY=${OPENAI_API_KEY:-dummy_key}
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app

  tests:
    build:
      context: .
      dockerfile: Dockerfile
    image: ai-structurizer-tests:latest
    container_name: ai-structurizer-tests
    environment:
      - PYTHONUNBUFFERED=1
      - OPENAI_API_KEY=dummy_key
      - PYTHONPATH=/app
    command: pytest -v
    volumes:
      - .:/app