name: CI/CD Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3️⃣ Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 4️⃣ Build Docker images (API + tests)
      - name: Build Docker images
        run: docker compose build

      # 5️⃣ Run tests using Docker Compose (mocked OpenAI)
      - name: Run tests
        run: docker compose run --rm tests

      # 6️⃣ Push API Docker image
      - name: Push Docker image
        run: |
          docker tag ai-structurizer dhiraj918106/ai-structurizer:latest
          docker push dhiraj918106/ai-structurizer:latest

      # 7️⃣ Success message
      - name: Deployment success
        run: echo "✅ Successfully built, tested, and pushed ai-structurizer to Docker Hub!"
