name: CI/CD Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Set up Python (optional for local tests)
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # 3️⃣ Install dependencies and run tests (optional)
      - name: Install dependencies & run tests
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pytest -v

      # 4️⃣ Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 5️⃣ Build and push Docker image
      - name: Build and push Docker image
        run: |
          docker build -t dhiraj918106/ai-structurizer:latest .
          docker push dhiraj918106/ai-structurizer:latest

      # 6️⃣ Success message
      - name: Deployment success
        run: echo "✅ Successfully built and pushed ai-structurizer to Docker Hub!"
